tunnel: 12675577-d94b-4a19-b1df-a86713dbaf80
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: api.vectracargo.com.br
    service: http://api:8000
    originRequest:
      connectTimeout: 30s
      keepAliveTimeout: 90s
      keepAliveConnections: 100
      http2Origin: false
      noTLSVerify: true

  - hostname: gymsite-api.vectracargo.com.br
    service: http://api:8000
    originRequest:
      connectTimeout: 30s
      keepAliveTimeout: 90s
      keepAliveConnections: 100
      http2Origin: false
      noTLSVerify: true

  - service: http_status:404
