tunnel: dbad2419-2271-42e1-840f-40864fa53298
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: api.vectracargo.com.br
    service: http://api:8000
    originRequest:
      connectTimeout: 30s
      keepAliveTimeout: 90s
      keepAliveConnections: 100
      http2Origin: false
      noTLSVerify: true

  - hostname: gymsite-api.vectracargo.com.br
    service: http://api:8000
    originRequest:
      connectTimeout: 30s
      keepAliveTimeout: 90s
      keepAliveConnections: 100
      http2Origin: false
      noTLSVerify: true

  - service: http_status:404
